remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [JavaMail TCK]
description: [Technology Compatibility Kit User's Guide for JavaMail API, Release 1.6]

# sidebar links url
links:
  source: https://github.com/eclipse-ee4j/javamail-tck
  download: https://github.com/eclipse-ee4j/javamail-tck/releases
  mailinglist: https://accounts.eclipse.org/mailing-list/javamail-dev
  #javadocs:
  docs: https://eclipse-ee4j.github.io/javamail-tck
  #faq:

include:
  - LICENSE.md
  - CONTRIBUTING.md
